// Mocks generated by Mockito 5.3.2 from annotations
// in crcrme_banque_stages/test/riskProxy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:crcrme_banque_stages/screens/ref_sst/common/proxy_ref_sst.dart'
    as _i2;
import 'package:crcrme_banque_stages/screens/ref_sst/common/risk_sst.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [risksProxy].
///
/// See the documentation for Mockito's code generation for more information.
class MockrisksProxy extends _i1.Mock implements _i2.risksProxy {
  MockrisksProxy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get parsedRisks => (super.noSuchMethod(
        Invocation.getter(#parsedRisks),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  set parsedRisks(Map<String, dynamic>? _parsedRisks) => super.noSuchMethod(
        Invocation.setter(
          #parsedRisks,
          _parsedRisks,
        ),
        returnValueForMissingStub: null,
      );
  @override
  dynamic fromJson(Map<String, dynamic>? riskList) =>
      super.noSuchMethod(Invocation.method(
        #fromJson,
        [riskList],
      ));
  @override
  List<_i3.CardSST> getList() => (super.noSuchMethod(
        Invocation.method(
          #getList,
          [],
        ),
        returnValue: <_i3.CardSST>[],
      ) as List<_i3.CardSST>);
}
